Unit Testing: React Testing Library
wwwdrt/math-magicians pull request #6
Opened 2023-06-17 22:12 UTC by wwwdrt

# 👋 Math Magicians: React Testing Library

> I'm looking forward to your feedback 🚀

Please feel free to reach out to me on Slack anytime. You can send me a direct message or give me a call. If you choose to call, please introduce yourself so I know who I'm speaking with. I'm here to help, so don't hesitate to get in touch 😁

<h3 align=center>⬇️</h3>

<div align="center">
  <a target="_blank" href="https://t.me/apexsec">
    <img src="https://img.shields.io/badge/-Message-2CA5E0?style=for-the-badge&logo=Telegram&logoColor=white" alt="Telegram">
  </a>
<a target="_blank" href="https://your-slack-link">
  <img src="https://img.shields.io/badge/-Slack-4A154B?style=for-the-badge&logo=Slack&logoColor=white" alt="Slack">
</a>
<a target="_blank" href="https://your-zoom-link">
  <img src="https://img.shields.io/badge/-Zoom-168FE5?style=for-the-badge&logo=Zoom&logoColor=white" alt="Zoom">
</a>
</div>

<br>

<div align="center">
  <img src="https://media2.giphy.com/media/13HgwGsXF0aiGY/giphy.gif?cid=ecf05e47drdxamgqh5qs2m9cwb2iozsx0q3c5veum57xf0j2&ep=v1_gifs_search&rid=giphy.gif&ct=g" />

### Latest project 🔥"[Ruby on Rails Blog](https://github.com/wwwdrt/rails_blog)"
</div>

# 📖 Getting Started

> In this part of the project I wrote unit tests for all of the components using react testing library.

2023-06-17 22:33 UTC, 1GORDON reviewed
##
## Hi @wwwdrt ✋

Good job so far!

Hello ✋, you have done well reaching this point of the milestone 🤝 . But there are some issues that you still need to work on to go to the next project but you are almost there!

### This project will be marked as Invalid and won't affect the number of your weekly reviews.

- [ ] You have submitted a project missing commits from your pair programming group. Kindly ensure your team members from your pair programming group commit to this pull request before you resubmit for review.

Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread and tag me `@1GORDON` if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think the code review was unfair, request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-18 00:20 UTC, abdulhamiid requested changes
# Status: Required Changes :recycle:
Hi Team 👋, 
![](https://media.giphy.com/media/UdaSUYClr92cjWpeVx/giphy.gif)
Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there! :running_man: :runner: 
<FEEL FREE TO CHANGE THIS MESSAGE TO YOUR PERSONAL WORDS>

## Highlights 🌟

- ✔️Write unit tests with React Testing Library.
- ✔️ Write unit tests with snapshots with Jest.

## Required Changes ♻️
_Please kindly check the comments under the review._

## Optional suggestions 🤷‍♂️
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._

Cheers, and Happy coding!👏👏👏

## Important Notes 📝
- Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
- Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-18 00:20 UTC, abdulhamiid commented on src/Components/Quotes.test.js
> +});
The test passes but I get the following warning in `src\Components\Quotes.js`:
![image](https://github.com/wwwdrt/math-magicians/assets/78251927/4ba9ac85-f575-42e8-bf82-3f283702bf78)

Kindly fix that to ensure that the app is running smoothly as it should  🛠💪.

2023-06-18 01:39 UTC, KanzaTahreem approved these changes
# Approved 🙌

Hi team 🙋‍♀️

Great work implementing the suggested changes 💪 **_Your project is COMPLETE! There is nothing else to say other than... it's time to merge it! 🚀 Congratulations!_**

<img src="https://media.tenor.com/xDHCe07zrocAAAAC/congrats-minions.gif"/>

## Highlights 🎯
There are some excellent points that you have made perfectly. Keep up the great work! 👏

-  ✅ All tests are passing, perfect!
-  ✅ Great work using the right Gitflow 
-  ✅ Warning is cleared, well done!
-  ✅ Linters are working properly, great job! 

## Optional suggestions ❕
N/A

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👨‍💻💻

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-19 10:41 UTC, merged